<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `megmdesi_betteralamancevolunteers`
//

// `megmdesi_betteralamancevolunteers`.`opportunity`
$opportunity = array(
  array('ID' => '1','Organization' => 'Alamance County Arts Council','Category' => 'Arts/Culture','Location' => '213 S. Main Street, Graham NC 27253','Time' => '9am-5pm','Description' => 'Since we have a staff of 5, it\'s a great opportunity for those interested in the arts to have real world experience at a local non-profit. Our Arts Council is quite vibrant given its size, drawing international exhibits every other year. ','Age Group' => '18-54'),
  array('ID' => '2','Organization' => 'Blakely Hall','Category' => 'Seniors','Location' => '489 Blakey Hall Lane, Elon NC 27244','Time' => '8am-4:30pm','Description' => 'To promote the social, emotional, psychological, spiritual, and physical well being of each resident in this long term care facility for the elderly. Opportunities for service are in working through the activity department to help meet individual needs of the residents and/or in providing support to children in an after-school environment.','Age Group' => '55+'),
  array('ID' => '3','Organization' => 'Boys and Girls Club','Category' => 'Youth','Location' => '807 Stockard Street, Burlington NC 27216','Time' => '10am-12pm 3pm-4:30pm','Description' => 'To enable all youth, especially those that need us the most, to reach their full potential as responsible and caring citizens. Service experiences are centered around tutoring children, working with children in a recreational environment and providing mentoring relationships to help meet individual needs. Service learning tutors should arrange schedule around Power Hour for after-school tutoring from 3:00-4:30.','Age Group' => '18-54'),
  array('ID' => '4','Organization' => 'Burlington Animal Services and Pet Adoption Center','Category' => 'Animals','Location' => '215 Stone Quarry Rd.Haw River, NC 27258','Time' => '9am-4:30pm','Description' => 'The center is committed to finding permanent loving homes for pets and provide education and awareness about being responsible pet owners. Volunteer times are 9-4:30, Mon-Fri, and 10-3:30 on Saturday. Volunteers are needed occasionally for special/public events. Outreach coordinator will contact volunteers as needed.','Age Group' => 'Under 18'),
  array('ID' => '5','Organization' => 'Children\'s Museum of Alamance','Category' => 'Arts/Culture','Location' => '217 South Main StreetGraham, NC 27253','Time' => '9am-5pm','Description' => 'The Children\'s Museum of Alamance County encourages children to exercise their curiosity, develop their imagination, and discover their world through exploration. We provide environments where children and adults are given a unique opportunity to play and create together. We promote learning and literacy through a wide array of multi-sensory, interactive, hands-on experiences. We instill in children a greater understanding of themselves and their world which surrounds them.','Age Group' => '55+'),
  array('ID' => '6','Organization' => 'Kernodle Senior Center','Category' => 'Seniors','Location' => 'PO Box 1358, Burlington NC 27216','Time' => '8am-4:30pm','Description' => 'The Center provides recreation and services to people 55 years and over. This active senior population participates in Senior Olympics, special classes, physical fitness, crafting and other opportunities at the center. A reduced cost lunch is offered daily. Service learners will have opportunities to interact with seniors in a variety of ways through activities and often may assist with planning an event for them, such as a Valentine?s party. This is a Burlington City run program under Parks and Recreation.','Age Group' => '18-54'),
  array('ID' => '7','Organization' => 'Cottage at Blakely','Category' => 'Seniors','Location' => '489 Blakely Hall Lane, Elon NC 27244','Time' => '8am-4pm','Description' => 'The Cottage at Blakey is a Assisted Living Memory Care Unit with 16 residents. We are looking for someone to assist with activities and special functions we have at The Cottage. Residents have limited memory but very physically active (cards, checkers, reading) and enjoy one on one interaction with others. Would like someone who would be comfortable working with dementia residents and finds a challenge in it. Professional dress is required.','Age Group' => '18-54'),
  array('ID' => '8','Organization' => 'Studio 1','Category' => 'Arts/Culture','Location' => '1332 Plaza Dr, Burlington NC 27215','Time' => '8am-5pm','Description' => 'Volunteers are needed Friday & Saturday evenings along with Sun afternoons to help with ticket sales & concessions. Administrative help is needed weekly between 8am & 5pm, and grant writing help is also appreciated.','Age Group' => '55+'),
  array('ID' => '9','Organization' => 'Humane Society of Alamance County','Category' => 'Animals','Location' => 'P.O. Box 3673, Burlington NC 27215','Time' => '','Description' => 'Volunteer by request. Adoption fairs on the first and third Saturday of every month.','Age Group' => 'Under 18'),
  array('ID' => '10','Organization' => 'Haw River Trail','Category' => 'Environment','Location' => '3916 R. Dean Coleman Road, Burlington NC 27215','Time' => '','Description' => 'Potential projects include volunteer organizing and programming, securing funds and marketing (PR). The cities of Burlington and Graham have partnered with Alamance County, Elon University, Preservation North Carolina and the Z. Smith Reynolds Foundation to fund a full-time position to coordinate conservation and trail efforts on the Upper Haw River. ','Age Group' => '18-54'),
  array('ID' => '11','Organization' => 'The ARC of Alamance County','Category' => 'People with Disabilities','Location' => 'PO Box 1275, Burlington NC 27216','Time' => '9am-1pm 4pm-6pm','Description' => 'Program works with developmentally disabled to better connect them with community and resources. Mondays 9-1 and Thursdays 4-6','Age Group' => '55+'),
  array('ID' => '12','Organization' => 'Special Olympics of Alamance County','Category' => 'People with Disabilities','Location' => '3916 R. Dean Coleman Rd, Burlington NC 27215','Time' => '8am-5pm','Description' => 'We have many hours that we offer programs. We have day hours for administrative tasks and special events, evening for practice, weekend for State Level Competition. Offering programs including Special Olympics, programs for the visually impaired and "heart felt" for adults with severe disabilities who are home bound. ','Age Group' => '18-54'),
  array('ID' => '13','Organization' => 'Sustainable Alamance','Category' => 'Environment','Location' => 'P.O. Box 298, Alamance, NC 27201','Time' => 'flexible','Description' => 'Volunteers will be working with indirect services, working with many county agencies, courts, faith based partners to identify, develop, and place ex-offenders in jobs, and new business ventures where they may work and even own one day. Also developing the marketing support for the community education, web site, brochures, etc. for the agency and','Age Group' => '18-54'),
  array('ID' => '14','Organization' => 'Family Abuse Services- Administration','Category' => 'Crisis Support','Location' => '1950 Martin Street, Burlington NC 27215','Time' => '8am-5pm','Description' => 'Program offering services to battered women and are committed to zero tolerance of domestic violence. Academic Service experiences are specific to Crisis line volunteer positions with required training.The service positions will be filled with training and phone hours directly spent on the line. Crisis line, shelter support or Some office work, and special projects.','Age Group' => '55+'),
  array('ID' => '15','Organization' => 'DreamAlign Ministries','Category' => 'Faith Based','Location' => '124 East Pine Street, Graham NC 27253','Time' => 'flexible','Description' => 'DreamAlign Ministries is a tax exempt 501(c)3 Non-Profit organization. We don\'t only want to function as a Non-Profit, we also shepherd the people that we help. Giving them assistance not only for today but for eternity. Programs include pantry,clothing closet and job resources.','Age Group' => 'Under 18'),
  array('ID' => '16','Organization' => 'First Presbyterian Church','Category' => 'Faith Based','Location' => '4397 Millstone Place, Burlington NC 27215','Time' => 'flexible','Description' => 'The Furniture Ministry at First Presbyterian Church in Burlington collects donations of gently used furniture and other households items and delivers them to needy families within Alamance County. The project is growing, and it is anticipated that other churches and organizations will soon be asked to join. With this growth, we need to develop communication materials, such as a Power Point presentation and Website, and other marketing strategies. It is in this capacity that we would like to include one or more volunteers who have the technical skills to assist with developing the communications materials and who are also learning the skills of marketing strategies and can help with this aspect of our mission.','Age Group' => '18-54'),
  array('ID' => '17','Organization' => 'Burlington Development Corporation','Category' => 'Community','Location' => '1209 Chandler Ct, Burlington NC 27217','Time' => '8am-5pm','Description' => 'The purpose of BDC is to provide housing, academic enrichment activities and economic opportunity programs and services for low-income individuals and families.','Age Group' => '55+'),
  array('ID' => '18','Organization' => 'Alamance Cares','Category' => 'Community','Location' => '3025 S. Church Street, Burlington NC 27216','Time' => 'M-F 9am-5pm','Description' => 'Students will help support the program with Education/Prevention at Elon and in the community, Information Services and Support Services. There are confidentiality issues that may limit a service learning student\'s ability to interact with clients. M-F 9-5','Age Group' => '55+')
);
